# Spring
# For custom endpoint exception handling
spring:
  # Profile
  profiles:
    active: dev
  # Datasource
  datasource:
    # Database
    url: ${SJ_COINS_SERVER_DATASOURCE_URL}
    username: ${SJ_COINS_SERVER_DATASOURCE_USERNAME}
    password: ${SJ_COINS_SERVER_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  flyway:
    baseline-on-migrate: true
    ignore-future-migration: true
    ignore-missing-migration: true

#seconds
eris:
  transaction:
    collector:
      interval: 2

logging:
  config: file:${SJ_COINS_SERVER_LOGGING_CONFIG_FILE}

# Application specific properties.
application:
  auth:
    server:
      url: ${SJ_COINS_SERVER_AUTH_SERVER_URL}
    client:
      id: ${SJ_COINS_SERVER_AUTH_CLIENT_ID}
      secret: ${SJ_COINS_SERVER_AUTH_CLIENT_SECRET}
    public-key-file: ${SJ_COINS_SERVER_AUTH_PUBKEY_PATH}
  fabric:
    client-url: ${SJ_COINS_SERVER_FABRIC_CLIENT_URL}
  organisation:
    name: coins
  treasury:
    account: sj_coin
  image:
    storage:
      path: ${SJ_COINS_SERVER_IMAGE_PATH}
    account:
      default-url: /account/default.png
