# Spring
# For custom endpoint exception handling

spring:
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  flyway:
    baseline-on-migrate: true
    ignore-future-migrations: true
    ignore-missing-migrations: true

logging:
  config: file:${HOME}/.coins/logback.xml
image:
  storage:
    path: ${HOME}/.coins/images
  account:
    default: /account/default.png