DROP TABLE transactions IF EXISTS;
DROP TABLE accounts IF EXISTS;

CREATE TABLE accounts
(
    ldap_id VARCHAR(255) NOT NULL PRIMARY KEY,
    amount DECIMAL(10)
);

INSERT INTO accounts (ldap_id, amount) VALUES ('account1', 100);
INSERT INTO accounts (ldap_id, amount) VALUES ('account2', 200);

CREATE TABLE transactions
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(255),
    destination_id VARCHAR(255),
    amount DECIMAL(10),
    comment LONGVARCHAR,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT account_fk FOREIGN KEY (account_id) REFERENCES accounts (ldap_id),
    CONSTRAINT destination_fk FOREIGN KEY (destination_id) REFERENCES accounts (ldap_id)
);
CREATE INDEX account_fk ON transactions (account_id);
CREATE INDEX destination_fk ON transactions (destination_id);