DROP TABLE eris IF EXISTS CASCADE;
DROP TABLE accounts IF EXISTS CASCADE;
DROP TABLE transactions IF EXISTS;
DROP TABLE tx_calling_data IF EXISTS;
DROP TABLE transaction_history IF EXISTS;
DROP TABLE instances IF EXISTS;
DROP TABLE contracts IF EXISTS;
DROP TABLE contract_type IF EXISTS;

CREATE TABLE accounts
(
  ldap_id      VARCHAR(255) NOT NULL PRIMARY KEY,
  full_name    VARCHAR(255),
  account_type VARCHAR(32) DEFAULT 'REGULAR',
  image        VARCHAR(255),
  is_new       BOOLEAN     DEFAULT 1,
  deleted      BOOLEAN     DEFAULT 0
);

CREATE TABLE transactions
(
  id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_ldap_id VARCHAR(255),
  destination_ldap_id VARCHAR(255),
  amount DECIMAL(10),
  comment VARCHAR(255),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  status VARCHAR(32) NOT NULL,
  error VARCHAR(255),
  remain DECIMAL(19,2),
  eris_transaction_id VARCHAR(255) ,
  CONSTRAINT account_fk FOREIGN KEY (account_ldap_id) REFERENCES accounts (ldap_id),
  CONSTRAINT destination_fk FOREIGN KEY (destination_ldap_id) REFERENCES accounts (ldap_id)
);

CREATE INDEX account_fk
  ON transactions (account_ldap_id);
CREATE INDEX destination_fk
  ON transactions (destination_ldap_id);
CREATE TABLE eris
(
  address         VARCHAR(255) PRIMARY KEY NOT NULL,
  priv_key        VARCHAR(255),
  pub_key         VARCHAR(255),
  type            INT,
  account_ldap_id VARCHAR(255),
  CONSTRAINT FK55s0o6jfa48iqty8bc1nxxrf2 FOREIGN KEY (account_ldap_id) REFERENCES accounts (ldap_id)
);
CREATE INDEX FK55s0o6jfa48iqty8bc1nxxrf2
  ON eris (account_ldap_id);
CREATE UNIQUE INDEX UKrpsbty0f34qu89n6juppia3ge
  ON eris (type, account_ldap_id);

CREATE TABLE transaction_history (
  id                    BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  block_number          BIGINT       DEFAULT NULL,
  chain_id              VARCHAR(255) DEFAULT NULL,
  function_name         VARCHAR(255) DEFAULT NULL,
  time                  DATETIME     DEFAULT NULL,
  amount                BIGINT DEFAULT NULL,
  caller_address        VARCHAR(255) DEFAULT NULL,
  caller_pub_key        VARCHAR(255) DEFAULT NULL,
  calling_data          VARCHAR(2500),
  contract_address      VARCHAR(255) DEFAULT NULL,
  fee                   BIGINT DEFAULT NULL,
  gas_limit             BIGINT DEFAULT NULL,
  is_deploy             BIT(1)       DEFAULT NULL,
  sequence              BIGINT DEFAULT NULL,
  signature VARCHAR(255) DEFAULT NULL,
  tx_id                 VARCHAR(255) DEFAULT NULL
);

CREATE TABLE tx_calling_data
(
  tx_id         BIGINT       NOT NULL,
  calling_value VARCHAR(255),
  function_name VARCHAR(255) NOT NULL,
  CONSTRAINT PRIMARY_KEY PRIMARY KEY (tx_id, function_name),
  CONSTRAINT FKcdwwj4qxq3unv7cveilenig5d FOREIGN KEY (tx_id) REFERENCES transaction_history (id)
);

CREATE TABLE contract_type
(
  type VARCHAR(255) PRIMARY KEY NOT NULL
);

CREATE TABLE contracts
(
  id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  abi CLOB,
  code CLOB,
  name VARCHAR(255),
  type VARCHAR(255),
  active bit(1) NOT NULL,
  CONSTRAINT FK9hxn5k55mpp0j3yqt1ej4of5y FOREIGN KEY (type) REFERENCES contract_type (type)
);

CREATE TABLE instances
(
  id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  address VARCHAR(255),
  contract_id BIGINT,
  name VARCHAR(255),
  CONSTRAINT FKhr2kxnlv3eb3x30dm2l9fpvkg FOREIGN KEY (contract_id) REFERENCES contracts (id)
);

ALTER TABLE instances ADD COLUMN account_ldap_id varchar(255) NOT NULL;

ALTER TABLE instances
  ADD CONSTRAINT FKhr2kxnlv3eb3x30dm2l9fpvdf FOREIGN KEY (account_ldap_id) REFERENCES accounts (ldap_id);